<?php

/**
 * Test: Nette\DI\Config\Adapters\NeonAdapter
 */

declare(strict_types=1);

use Mallgroup\DI\Config\Adapters\EnvironmentAdapter;
use Nette\DI\Config;
use Nette\DI\Definitions\Statement;
use Tester\Assert;


require __DIR__ . '/../bootstrap.php';

define('TEMP_FILE', getTempDir() . '/cfg.env');


$config = new Config\Loader();
$config->addAdapter('env', EnvironmentAdapter::class);


$cfg = '
service_user: ::string(secret_user)
service_password: ::string(secret_password, true)
service_port: ::int(1234)
service_nonstring: ::nonstring(1234)
service_active: ::bool(\'false\')
';
$data = $config->load(Tester\FileMock::create($cfg, 'env'));
Assert::equal([
                  'parameters' => [
                      'env' =>
                          [
                              'service_user' => 'secret_user',
                              'service_password' => new Statement(
                                  'Mallgroup\Environment::string',
                                  ['SERVICE_PASSWORD', 'secret_password']
                              ),
                              'service_port' => 1234,
                              'service_nonstring' => '1234',
                              'service_active' => false
                          ]
                  ]
              ], $data);


$config->save($data, TEMP_FILE);
Assert::match(
    <<<'EOD'
	# generated by Nette

	service_user: secret_user
	service_password: ::string(secret_password, true)
	service_port: 1234
	service_nonstring: "1234"
	service_active: false
	EOD
    ,
    file_get_contents(TEMP_FILE)
);
